services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${WEB_PORT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-app.rule=Host(${WEB})
      - traefik.http.routers.web-app.entrypoints=websecure
      - traefik.http.routers.web-app.tls.certResolver=letsencrypt
      - traefik.http.services.web-app.loadbalancer.server.port=${WEB_PORT}
    depends_on:
      - api
    restart: always
    networks:
      - dokploy-network
    env_file:
      - .env

  api:
    build:
      context: ./libs/php
      dockerfile: Dockerfile
      args:
        MAPBOX_USERNAME: ${MAPBOX_USERNAME}
        GEO_USERNAME: ${GEO_USERNAME}
        IPINFO_TOKEN: ${IPINFO_TOKEN}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASS: ${DB_PASS}
        MAPBOX_TOKEN_PHP: ${MAPBOX_TOKEN_PHP}
        MAPBOX_TOKEN_DEFAULT: ${MAPBOX_TOKEN_DEFAULT}
    restart: always
    env_file:
      - .env
    networks:
      - dokploy-network
      

  tileserver:
    build:
      context: ./tileserver/
      dockerfile: Dockerfile
      args: {}
    restart: always
    networks:
      - dokploy-network

#   db:
#     build:
#       context: ./db/
#       dockerfile: Dockerfile
#       args: {}
#     environment:
#       MYSQL_PASSWORD: ${DB_PASS}
#       MYSQL_USER: ${DB_USERNAME}
#       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
#     restart: always
#     volumes:
#       - db_data:/var/lib/mysql
#     expose:
#       - ${DB_PORT}
#     env_file:
#       - .env
#     networks:
#       - dokploy-network

# volumes:
#   db_data:

networks:
  dokploy-network:
    external: true
