services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${WEB_PORT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.web2-app.rule=Host(${WEB})
      - traefik.http.routers.web2-app.entrypoints=websecure
      - traefik.http.routers.web2-app.tls.certResolver=letsencrypt
      - traefik.http.services.web2-app.loadbalancer.server.port=${WEB_PORT}
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - dokploy-network
    env_file:
      - .env

  api:
    build:
      context: ./libs/php
      dockerfile: Dockerfile
      args:
        MAPBOX_USERNAME: ${MAPBOX_USERNAME}
        GEO_USERNAME: ${GEO_USERNAME}
        IPINFO_TOKEN: ${IPINFO_TOKEN}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASS: ${DB_PASS}
        MAPBOX_TOKEN_PHP: ${MAPBOX_TOKEN_PHP}
        MAPBOX_TOKEN_DEFAULT: ${MAPBOX_TOKEN_DEFAULT}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.api2-app.rule=Host(${API})
      - traefik.http.routers.api2-app.entrypoints=websecure
      - traefik.http.routers.api2-app.tls.certResolver=letsencrypt
      - traefik.http.services.api2-app.loadbalancer.server.port=${API_PORT}
    env_file:
      - .env
    networks:
      - dokploy-network

  tileserver:
    build:
      context: ./tileserver/
      dockerfile: Dockerfile
      args: {}
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.tile-app.rule=Host(${TILE}) && PathPrefix(`/data`)      
      - traefik.http.routers.tile-app.entrypoints=websecure
      - traefik.http.routers.tile-app.tls.certResolver=letsencrypt
      - traefik.http.services.tile-app.loadbalancer.server.port=${TILE_PORT}


networks:
  dokploy-network:
    external: true
