services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${WEB_PORT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-app.rule=Host(${WEB})
      - traefik.http.routers.web-app.entrypoints=websecure
      - traefik.http.routers.web-app.tls.certResolver=letsencrypt
      - traefik.http.services.web-app.loadbalancer.server.port=${WEB_PORT}
    container_name: web
    depends_on:
      - api
    restart: always
    networks:
      - dokploy-network
    env_file:
      - .env

  api:
    build:
      context: ./libs/php
      dockerfile: Dockerfile
      args:
        MAPBOX_USERNAME: ${MAPBOX_USERNAME}
        GEO_USERNAME: ${GEO_USERNAME}
        IPINFO_TOKEN: ${IPINFO_TOKEN}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASS: ${DB_PASS}
        MAPBOX_TOKEN_PHP: ${MAPBOX_TOKEN_PHP}
        MAPBOX_TOKEN_DEFAULT: ${MAPBOX_TOKEN_DEFAULT}
    expose:
      - ${API_PORT}
    container_name: api
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-app.rule=Host(${API})
      - traefik.http.routers.api-app.entrypoints=websecure
      - traefik.http.routers.api-app.tls.certResolver=letsencrypt
      - traefik.http.services.api-app.loadbalancer.server.port=${API_PORT}

  tileserver:
    build:
      context: ./tileserver/
      dockerfile: Dockerfile
      args: {}
    restart: always
    expose:
      - ${TILE_PORT}
    container_name: tileserver
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-app.rule=Host(${TILE})
      - traefik.http.routers.api-app.entrypoints=websecure
      - traefik.http.routers.api-app.tls.certResolver=letsencrypt
      - traefik.http.services.api-app.loadbalancer.server.port=${TILE_PORT}
 

  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
      args: {}
    container_name: db
    environment:
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    restart: always
    volumes:
      - ../files/db_data:/var/lib/mysql
    expose:
      - ${DB_PORT}
    env_file:
      - .env
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-app.rule=Host(${DB})
      - traefik.http.routers.api-app.entrypoints=websecure
      - traefik.http.routers.api-app.tls.certResolver=letsencrypt
      - traefik.http.services.api-app.loadbalancer.server.port=${DB_PORT}

volumes:
  db_data:

networks:
  dokploy-network:
    external: true
